version: '2'
services:

  postgres:
    image: postgres

  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    build: .
    links:
      - postgres
      - elasticsearch
      - rabbitmq
      - qgis-server
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE={{project_name}}.settings
      - ALLOWED_HOSTS=['django',]
      - QGIS_SERVER_URL=http://qgis-server/cgi-bin/qgis_mapserv.fcgi

  celery:
    build: .
    links:
      - rabbitmq
      - postgres
      - elasticsearch
      - qgis-server
    command: celery worker --app={{project_name}}.celeryapp:app -B -l INFO
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - QGIS_SERVER_URL=http://qgis-server/cgi-bin/qgis_mapserv.fcgi
      - DJANGO_SETTINGS_MODULE={{project_name}}.settings
      - ALLOWED_HOSTS=['django',]
      - C_FORCE_ROOT=1

  qgis-server:
    image: waybarrios/qgis-server
    volumes:
      - '../code/geonode_qgis_server/geonode_qgis_server:/usr/src/geonode_qgis_server'
    command:
      - /setup-qgis-server.sh

  nginx:
    image: terranodo/nginx:geoserver
    links:
      - django
      - geoserver
    ports:
      - "80:80"
